raw_data = np.random.randint(low=0, high=2, size=(1000, 6)
data = pd.DataFrame(raw_data, columns=['A', 'R', 'J', 'G', 'L', 'Q'])
student_model = BayesianModel()
student_model.fit(data, esitmator=BayesianEstimator)
student_model.get_cpds()
student_model.get_nodes()
student_model.get_edges()